# Generated by Django 4.2.3 on 2023-07-06 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_bookreview_book'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genrecount',
            options={'verbose_name_plural': 'Genre Counts'},
        ),
    ]
