# Generated by Django 4.2.3 on 2023-07-06 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_genrecount_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eicount',
            options={'verbose_name_plural': 'EI Counts'},
        ),
        migrations.AlterModelOptions(
            name='fillingcount',
            options={'verbose_name_plural': 'Feeling Counts'},
        ),
        migrations.AlterModelOptions(
            name='ftcount',
            options={'verbose_name_plural': 'FT Counts'},
        ),
        migrations.AlterModelOptions(
            name='jpcount',
            options={'verbose_name_plural': 'JP Counts'},
        ),
        migrations.AlterModelOptions(
            name='nscount',
            options={'verbose_name_plural': 'NS Counts'},
        ),
    ]
