# Generated by Django 4.2.3 on 2023-07-06 13:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0004_alter_eicount_options_alter_fillingcount_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookreview',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
