# Generated by Django 4.2.3 on 2023-07-06 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_bookreview_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookreview',
            name='pickpage',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bookreview',
            name='pickwriting',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
