# Generated by Django 4.2.3 on 2023-07-12 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_alter_bookreview_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookreview',
            name='author',
            field=models.CharField(default='N', max_length=255),
        ),
    ]
