# Generated by Django 4.2.3 on 2023-07-12 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_alter_bookreview_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookreview',
            name='created_at',
        ),
    ]
