# Generated by Django 4.2.3 on 2023-07-14 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0013_alter_book_author_alter_book_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookreview',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
